import { useEffect, useState } from 'react'
import Head from 'next/head'
import { useSession } from 'next-auth/react'
import connection from '../utils/db'
import { Inter } from '@next/font/google'
import { signIn } from 'next-auth/react'
import Posts from './Posts'

export default function Home({ posts }) {
	const { status, data } = useSession()

	if (status === 'unauthenticated')
		return (
			<>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<button
					onClick={() => {
						signIn()
					}}
				>
					Login
				</button>
				<Posts posts={posts} />
			</>
		)

	if (status === 'authenticated')
		return (
			<>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<h1>Hello {data.user.name}</h1>
				<Posts posts={posts} />
			</>
		)
}

export async function getStaticProps() {
	const [usersPosts, fields] = await connection.promise().query('SELECT * FROM userposts')
	const posts = JSON.parse(JSON.stringify(usersPosts))
	return {
		props: {
			posts,
		},
	}
}
