import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import connection from '../utils/db'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
      <nav>
        <Link href='loginPage'>Log In</Link>
      </nav>
			<main className={styles.main}>
				<div>
					<h1>My data from MySQL:</h1>
					<div className={styles.grid}>
						{data.map((item) => (
							<div className={styles.card} key={item.post_id}>
								<h3>{item.title}</h3>
								<p>{item.content}</p>
                <button>Read More</button>
								{/* <span>Password: {item.password}</span> */}
                <small>{item.date_created}</small>
							</div>
						))}
					</div>
				</div>
			</main>
		</>
	)
}

export async function getStaticProps() {
	const [posts, fields] = await connection.promise().query('SELECT * FROM userposts')
	const data = JSON.parse(JSON.stringify(posts))
	return {
		props: {
			data,
		},
	}
}
