import Head from 'next/head'
import connection from '../utils/db'
import { Inter } from '@next/font/google'
import Posts from './Posts'
import Navbar from '@/components/Navbar'

export default function Home({ posts }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Posts posts={posts} />
		</>
	)
}

export async function getStaticProps() {
	const [usersPosts] = await connection.promise().query('SELECT * FROM userposts ORDER BY post_id desc')
	const posts = JSON.parse(JSON.stringify(usersPosts))
	return {
		props: {
			posts,
		},
	}
}
